services:
  - type: web
    name: electron-chat-backend
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
