app:
  name: ota-radio-backend
  type: web
  env: node
  region: oregon
  plan: free
  branch: main
  buildCommand: npm install
  startCommand: npm start
  autoDeploy: true
  envVars:
    - key: NODE_ENV
      value: production
